#!/usr/bin/env bash
# Build Gearmulator JE-8086 VST3 from the fork submodule (Release).
# ROM is not required to compile; runtime needs GEARMULATOR_ROM_DIR for audio.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
GEARMULATOR_DIR="${REPO_ROOT}/gearmulator-lane/gearmulator"
BUILD_DIR="${REPO_ROOT}/gearmulator-lane/build-je8086-vsti"
JOBS="${GEARMULATOR_BUILD_JOBS:-$(nproc)}"
SYNTH="${GEARMULATOR_VSTI:-JE8086}"

if [[ ! -f "${GEARMULATOR_DIR}/CMakeLists.txt" ]]; then
  echo "Missing ${GEARMULATOR_DIR}. Run:" >&2
  echo "  git submodule update --init --recursive gearmulator-lane/gearmulator" >&2
  exit 1
fi

git -C "${REPO_ROOT}" submodule update --init --recursive gearmulator-lane/gearmulator

mkdir -p "${BUILD_DIR}"

case "${SYNTH}" in
  JE8086|je8086)
    CMAKE_SYNTH_FLAGS=(
      -Dgearmulator_SYNTH_JE8086=ON
      -Dgearmulator_SYNTH_OSIRUS=OFF
      -Dgearmulator_SYNTH_OSTIRUS=OFF
      -Dgearmulator_SYNTH_VAVRA=OFF
      -Dgearmulator_SYNTH_XENIA=OFF
      -Dgearmulator_SYNTH_NODALRED2X=OFF
      -Dgearmulator_SYNTH_88EMU=OFF
    )
    JUCE_TARGET="jeJucePlugin_VST3"
    PRODUCT="JE8086"
    ;;
  *)
    echo "Unsupported GEARMULATOR_VSTI=${SYNTH} (only JE8086 for now)" >&2
    exit 1
    ;;
esac

cmake "${GEARMULATOR_DIR}" -B "${BUILD_DIR}" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_CXX_COMPILER="${CMAKE_CXX_COMPILER:-g++-12}" \
  -DCMAKE_C_COMPILER="${CMAKE_C_COMPILER:-gcc-12}" \
  -Dgearmulator_BUILD_JUCEPLUGIN=ON \
  -Dgearmulator_BUILD_JUCEPLUGIN_CLAP=OFF \
  -Dgearmulator_BUILD_JUCEPLUGIN_LV2=OFF \
  "${CMAKE_SYNTH_FLAGS[@]}"

cmake --build "${BUILD_DIR}" --target "${JUCE_TARGET}" -j"${JOBS}"

# JUCE / Gearmulator output layouts (Linux)
VST3_CANDIDATES=(
  "${GEARMULATOR_DIR}/bin/plugins/Release/VST3/${PRODUCT}.vst3"
  "${BUILD_DIR}/source/ronaldo/je8086/jeJucePlugin/${PRODUCT}_artefacts/Release/VST3/${PRODUCT}.vst3"
  "${BUILD_DIR}/bin/plugins/Release/VST3/${PRODUCT}.vst3"
)

VST3_PATH=""
for c in "${VST3_CANDIDATES[@]}"; do
  if [[ -e "${c}" ]]; then
    VST3_PATH="${c}"
    break
  fi
done

if [[ -z "${VST3_PATH}" ]]; then
  VST3_PATH="$(find "${BUILD_DIR}" -path "*VST3*${PRODUCT}.vst3" -print -quit 2>/dev/null || true)"
fi

if [[ -z "${VST3_PATH}" || ! -e "${VST3_PATH}" ]]; then
  echo "Build finished but VST3 bundle not found under ${BUILD_DIR}" >&2
  find "${BUILD_DIR}" -name "*.vst3" 2>/dev/null | head -20 >&2 || true
  exit 1
fi

ENV_FILE="${REPO_ROOT}/gearmulator-lane/.gearmulator-vsti.env"
VST3_ABS="$(cd "$(dirname "${VST3_PATH}")" && pwd)/$(basename "${VST3_PATH}")"
cat > "${ENV_FILE}" <<EOF
# Generated by scripts/gearmulator/build-gearmulator-vsti.sh — source in shell sessions
export GEARMULATOR_JE8086_VST3="${VST3_ABS}"
export GEARMULATOR_VSTI_BUILD_DIR="${BUILD_DIR}"
EOF

echo "Built VST3: ${VST3_ABS}"
echo "Wrote ${ENV_FILE}"
echo "Capture example:"
echo "  source gearmulator-lane/.gearmulator-vsti.env"
echo "  python3 scripts/gearmulator/render_multisample_dawdreamer.py --plugin \"\${GEARMULATOR_JE8086_VST3}\" ..."
