#!/usr/bin/env bash
# Build Gearmulator Osirus FX VST3 (Access Virus effect; separate from Osirus synth).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
GEARMULATOR_DIR="${REPO_ROOT}/gearmulator-lane/gearmulator"
BUILD_DIR="${REPO_ROOT}/gearmulator-lane/build-osirus-fx"
JOBS="${GEARMULATOR_BUILD_JOBS:-$(nproc)}"

if [[ ! -f "${GEARMULATOR_DIR}/CMakeLists.txt" ]]; then
  echo "Missing submodule. Run: git submodule update --init --recursive gearmulator-lane/gearmulator" >&2
  exit 1
fi

git -C "${REPO_ROOT}" submodule update --init --recursive gearmulator-lane/gearmulator

mkdir -p "${BUILD_DIR}"

cmake "${GEARMULATOR_DIR}" -B "${BUILD_DIR}" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_CXX_COMPILER="${CMAKE_CXX_COMPILER:-g++-12}" \
  -DCMAKE_C_COMPILER="${CMAKE_C_COMPILER:-gcc-12}" \
  -Dgearmulator_BUILD_JUCEPLUGIN=ON \
  -Dgearmulator_BUILD_FX_PLUGIN=ON \
  -Dgearmulator_BUILD_JUCEPLUGIN_CLAP=OFF \
  -Dgearmulator_BUILD_JUCEPLUGIN_LV2=OFF \
  -Dgearmulator_SYNTH_OSIRUS=ON \
  -Dgearmulator_SYNTH_OSTIRUS=OFF \
  -Dgearmulator_SYNTH_VAVRA=OFF \
  -Dgearmulator_SYNTH_XENIA=OFF \
  -Dgearmulator_SYNTH_NODALRED2X=OFF \
  -Dgearmulator_SYNTH_JE8086=OFF \
  -Dgearmulator_SYNTH_88EMU=OFF

cmake --build "${BUILD_DIR}" --target osirusJucePlugin_FX_VST3 -j"${JOBS}"

PRODUCT="OsirusFX"
VST3_CANDIDATES=(
  "${GEARMULATOR_DIR}/bin/plugins/Release/VST3/${PRODUCT}.vst3"
  "${BUILD_DIR}/source/axel/osirusJucePlugin/${PRODUCT}_artefacts/Release/VST3/${PRODUCT}.vst3"
)

VST3_PATH=""
for c in "${VST3_CANDIDATES[@]}"; do
  if [[ -e "${c}" ]]; then
    VST3_PATH="${c}"
    break
  fi
done

if [[ -z "${VST3_PATH}" ]]; then
  VST3_PATH="$(find "${GEARMULATOR_DIR}/bin" "${BUILD_DIR}" -path "*Osirus*FX*.vst3" -print -quit 2>/dev/null || true)"
fi

if [[ -z "${VST3_PATH}" || ! -e "${VST3_PATH}" ]]; then
  echo "Osirus FX VST3 not found after build" >&2
  find "${BUILD_DIR}" -name "*.vst3" 2>/dev/null | head -10 >&2 || true
  exit 1
fi

VST3_ABS="$(cd "$(dirname "${VST3_PATH}")" && pwd)/$(basename "${VST3_PATH}")"
ENV_FILE="${REPO_ROOT}/gearmulator-lane/.gearmulator-osirus-fx.env"

cat > "${ENV_FILE}" <<EOF
# Generated by scripts/gearmulator/build-gearmulator-osirus-fx.sh
export GEARMULATOR_OSIRUS_FX_VST3="${VST3_ABS}"
export INSTRUMENTS_ALWAYS_OSIRUS_FX=1
EOF

echo "Built Osirus FX VST3: ${VST3_ABS}"
echo "Wrote ${ENV_FILE}"
echo "Source in shell: source gearmulator-lane/.gearmulator-osirus-fx.env"
