/* Auto-generated by tools/mkii/scaffold-mkii.py — edit dev_id/unit_id before release. */
#include "unit_osc.h"

const __unit_header unit_header_t unit_header = {
    .header_size = sizeof(unit_header_t),
    .target = UNIT_TARGET_PLATFORM | k_unit_module_osc,
    .api = UNIT_API_VERSION,
    .dev_id = 0x0U,
    .unit_id = 0x0U,
    .version = 0x00010000U,
    .name = "Sub Phatty",
    .num_params = 9,
    .params = {
        {0, 1023, 0, 40, k_unit_param_type_none, 0, 0, 0, {"VIBE"}},
        {0, 1023, 0, 55, k_unit_param_type_none, 0, 0, 0, {"OSCM"}},
        {0, 1023, 0, 22, k_unit_param_type_none, 0, 0, 0, {"DETU"}},
        {0, 1023, 0, 58, k_unit_param_type_none, 0, 0, 0, {"P03X"}},
        {0, 1023, 0, 42, k_unit_param_type_none, 0, 0, 0, {"DRIV"}},
        {0, 1023, 0, 18, k_unit_param_type_none, 0, 0, 0, {"GLID"}},
        {0, 1023, 0, 8, k_unit_param_type_none, 0, 0, 0, {"ATTA"}},
        {0, 1023, 0, 36, k_unit_param_type_none, 0, 0, 0, {"DECA"}},
        {0, 1023, 0, 32, k_unit_param_type_none, 0, 0, 0, {"RELE"}},
        {0, 0, 0, 0, k_unit_param_type_none, 0, 0, 0, {""}},
    },
};
