#!/usr/bin/env python3
"""
Generate an NTS-1 mkII (logue SDK v2) oscillator project from a v1 unit folder.

Output: src/mkii/oscillators/<slug>/

Requires LOGUE_SDK for copying wasm.cc from dummy-osc (optional with --skip-wasm).
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
MKII_OUT = REPO_ROOT / "src" / "mkii" / "oscillators"
V1_ROOT = REPO_ROOT / "src" / "oscillators"

# mkII short names: max 4 characters per param label
def short_label(name: str, index: int) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9]", "", name.upper())
    if len(cleaned) >= 4:
        return cleaned[:4]
    return f"P{index:02d}"[:4].ljust(4, "X")[:4]


def v1_default_to_mkii(init_v1: int, max_v1: int) -> int:
    if max_v1 <= 0:
        return 0
    v = int(round(init_v1 * 1023.0 / max_v1))
    return max(0, min(1023, v))


def load_manifest(unit_dir: Path) -> dict:
    with (unit_dir / "manifest.json").open(encoding="utf-8") as f:
        return json.load(f)


def find_v1_source(unit_dir: Path) -> str | None:
    for pat in ("*.cc",):
        for p in sorted(unit_dir.glob(pat)):
            if p.name in ("wasm.cc", "unit.cc"):
                continue
            return p.name
    return None


def render_header_c(name: str, params: list, defaults: list[int]) -> str:
    lines = [
        '/* Auto-generated by tools/mkii/scaffold-mkii.py — edit dev_id/unit_id before release. */',
        '#include "unit_osc.h"',
        "",
        "const __unit_header unit_header_t unit_header = {",
        "    .header_size = sizeof(unit_header_t),",
        "    .target = UNIT_TARGET_PLATFORM | k_unit_module_osc,",
        "    .api = UNIT_API_VERSION,",
        "    .dev_id = 0x0U,",
        "    .unit_id = 0x0U,",
        "    .version = 0x00010000U,",
        f'    .name = "{name[:15]}",',
        f"    .num_params = {len(params)},",
        "    .params = {",
    ]
    for i, (pname, pmin, pmax, _unit) in enumerate(params):
        d = defaults[i] if i < len(defaults) else v1_default_to_mkii(int(pmin), int(pmax) if int(pmax) > 0 else 100)
        # string-type params (small integer max) need special handling later
        ptype = "k_unit_param_type_none"
        mk_max = 1023
        mk_def = d
        if int(pmax) <= 16 and int(pmax) > 2:
            ptype = "k_unit_param_type_strings"
            mk_max = int(pmax)
            mk_def = min(mk_def, mk_max)
        lines.append(
            f'        {{{0}, {mk_max}, 0, {mk_def}, {ptype}, 0, 0, 0, {{"{short_label(pname, i)}"}}}},'
        )
    for _ in range(10 - len(params)):
        lines.append('        {0, 0, 0, 0, k_unit_param_type_none, 0, 0, 0, {""}},')
    lines.append("    },")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def render_osc_h(
    project: str,
    params: list,
    v1_rel: str,
    v1_source: str | None,
    preset_defaults: list[int],
) -> str:
    enum_entries = "\n".join(
        f"    {re.sub(r'[^A-Za-z0-9_]', '_', p[0].upper().replace(' ', '_'))} = {i}U,"
        for i, p in enumerate(params)
    )
    set_param_cases = []
    for i, (pname, pmin, pmax, _) in enumerate(params):
        ident = re.sub(r"[^A-Za-z0-9_]", "_", pname.upper().replace(" ", "_"))
        if int(pmax) <= 16 and int(pmax) > 2:
            set_param_cases.append(
                f"    case {ident}:\n      params_.p{i} = static_cast<uint32_t>(value);\n      break;"
            )
        else:
            set_param_cases.append(
                f"    case {ident}:\n      params_.p{i} = param_10bit_to_f32(value);\n      break;"
            )
    defaults = preset_defaults[: len(params)]
    while len(defaults) < len(params):
        defaults.append(0)

    init_lines = []
    for i in range(len(params)):
        pmax = int(params[i][2])
        if pmax <= 16 and pmax > 2:
            init_lines.append(
                f"      p{i} = static_cast<float>({min(defaults[i], pmax)});"
            )
        else:
            mk = v1_default_to_mkii(defaults[i], pmax if pmax > 0 else 100)
            init_lines.append(f"      p{i} = param_10bit_to_f32({mk});")
    init_body = "\n".join(init_lines)

    return f"""#pragma once
/* mkII oscillator — PORT DSP from v1: {v1_rel}/{v1_source or '*.cc'}
 * Replace process() body with your mkI OSC_CYCLE logic (float out, osc_w0f pitch).
 */
#include "processor.h"
#include "unit_osc.h"

class Osc : public Processor {{
public:
  uint32_t getBufferSize() const override final {{ return 0; }}

  enum {{
{enum_entries}
    NUM_PARAMS
  }};

  struct Params {{
    float p0;
    float p1;
    float p2;
    float p3;
    float p4;
    float p5;
    float p6;
    float p7;
    float p8;
    void reset() {{
{init_body}
    }}
    Params() {{ reset(); }}
  }};

  void setParameter(uint8_t index, int32_t value) override final {{
    switch (index) {{
{chr(10).join(set_param_cases)}
    default:
      break;
    }}
  }}

  const char *getParameterStrValue(uint8_t index, int32_t value) const override final {{
    (void)index;
    (void)value;
    return nullptr;
  }}

  void init(float *) override final {{
    params_.reset();
    phasor_ = 0.f;
    w0_ = 0.f;
  }}

  void setPitch(float w0) {{ w0_ = w0; }}
  void setShapeLfo(float lfo) {{ (void)lfo; }}

  void process(const float *__restrict in, float *__restrict out, uint32_t frames) override final {{
    const Params p = params_;
    for (const float *out_end = out + frames; out != out_end; in += 2, out += 1) {{
      phasor_ = fmodf(phasor_ + w0_, 1.f);
      const float shape = p.p0;
      const float saw = 2.f * phasor_ - 1.f;
      out[0] = osc_sinf(phasor_) * (1.f - shape) + saw * shape;
    }}
  }}

private:
  Params params_;
  float w0_;
  float phasor_;
}};
"""


def render_config_mk(project: str, extra_sources: list[str]) -> str:
    cxx = ["unit.cc"] + extra_sources
    return f"""##############################################################################
# Configuration for Makefile — generated by scaffold-mkii.py
#

PROJECT := {project}
PROJECT_TYPE := osc

UCSRC = header.c
UCXXSRC = {' '.join(cxx)}

UINCDIR =
ULIBDIR =
ULIBS = -lm
UDEFS =
"""


def render_makefile() -> str:
    return """##############################################################################
# NTS-1 mkII unit — builds against LOGUE_SDK platform tree.
#
#   export LOGUE_SDK=/path/to/logue-sdk
#   make
#

LOGUE_SDK ?= $(error LOGUE_SDK is not set)
NTS1_MKII := $(LOGUE_SDK)/platform/nts-1_mkii

PROJECT_ROOT := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

# Point SDK paths at nts-1_mkii (repo projects are not under platform/nts-1_mkii/).
COMMON_INC_PATH := $(NTS1_MKII)/common
COMMON_SRC_PATH := $(NTS1_MKII)/common
LDDIR := $(NTS1_MKII)/ld
EXTDIR := $(LOGUE_SDK)/platform/ext
TOOLSDIR := $(LOGUE_SDK)/tools

include $(NTS1_MKII)/dummy-osc/Makefile
"""


def osc_h_is_port_complete(path: Path) -> bool:
    if not path.is_file():
        return False
    text = path.read_text(encoding="utf-8")
    return "PORT_COMPLETE" in text or "mkII port of" in text


def render_unit_cc(logue_sdk: Path | None) -> str:
    if logue_sdk:
        sdk_unit = logue_sdk / "platform" / "nts-1_mkii" / "dummy-osc" / "unit.cc"
        if sdk_unit.is_file():
            return sdk_unit.read_text(encoding="utf-8")
    return """#include "osc.h"
#include "unit_osc.h"
#include "utils/int_math.h"

static Osc s_osc_instance;
static int32_t cached_values[UNIT_OSC_MAX_PARAM_COUNT];
static const unit_runtime_osc_context_t *context;

#define q31_to_f32_c 4.65661287307739e-010f
#define q31_to_f32(q) ((float)(q) * q31_to_f32_c)

__unit_callback int8_t unit_init(const unit_runtime_desc_t *desc) {
  if (!desc) return k_unit_err_undef;
  if (desc->target != unit_header.target) return k_unit_err_target;
  if (!UNIT_API_IS_COMPAT(desc->api)) return k_unit_err_api_version;
  if (desc->samplerate != s_osc_instance.getSampleRate()) return k_unit_err_samplerate;
  if (desc->input_channels != 2 || desc->output_channels != 1) return k_unit_err_geometry;
  context = static_cast<const unit_runtime_osc_context_t *>(desc->hooks.runtime_context);
  for (int id = 0; id < UNIT_OSC_MAX_PARAM_COUNT; ++id)
    cached_values[id] = static_cast<int32_t>(unit_header.params[id].init);
  return k_unit_err_none;
}

__unit_callback void unit_teardown() { s_osc_instance.teardown(); }
__unit_callback void unit_reset() { s_osc_instance.reset(); }
__unit_callback void unit_resume() { s_osc_instance.resume(); }
__unit_callback void unit_suspend() { s_osc_instance.suspend(); }

__unit_callback void unit_render(const float *in, float *out, uint32_t frames) {
  s_osc_instance.setPitch(osc_w0f_for_note((context->pitch) >> 8, context->pitch & 0xFF));
  s_osc_instance.setShapeLfo(q31_to_f32(context->shape_lfo));
  s_osc_instance.process(in, out, frames);
}

__unit_callback void unit_set_param_value(uint8_t id, int32_t value) {
  value = clipminmaxi32(unit_header.params[id].min, value, unit_header.params[id].max);
  cached_values[id] = value;
  s_osc_instance.setParameter(id, value);
}

__unit_callback int32_t unit_get_param_value(uint8_t id) { return cached_values[id]; }
__unit_callback const char *unit_get_param_str_value(uint8_t id, int32_t value) {
  value = clipminmaxi32(unit_header.params[id].min, value, unit_header.params[id].max);
  return s_osc_instance.getParameterStrValue(id, value);
}
__unit_callback void unit_note_on(uint8_t note, uint8_t velo) { s_osc_instance.noteOn(note, velo); }
__unit_callback void unit_note_off(uint8_t note) { s_osc_instance.noteOff(note); }
__unit_callback void unit_all_note_off() { s_osc_instance.allNoteOff(); }
__unit_callback void unit_set_tempo(uint32_t tempo) {
  float bpm = (tempo >> 16) + (tempo & 0xFFFF) / static_cast<float>(0x10000);
  s_osc_instance.setTempo(bpm);
}
__unit_callback void unit_tempo_4ppqn_tick(uint32_t counter) { s_osc_instance.tempo4ppqnTick(counter); }
__unit_callback void unit_pitch_bend(uint16_t bend) { s_osc_instance.pitchBend(bend); }
__unit_callback void unit_channel_pressure(uint8_t press) { s_osc_instance.channelPressure(press); }
__unit_callback void unit_aftertouch(uint8_t note, uint8_t press) { s_osc_instance.aftertouch(note, press); }
"""


def render_porting_readme(slug: str, v1_rel: str, v1_source: str | None) -> str:
    return f"""# mkII port: {slug}

## Status

Scaffold only — `osc.h` plays a placeholder tone until you port DSP.

## Finish the port

1. Open v1 source: `src/{v1_rel}/{v1_source or '*.cc'}`
2. Copy float math from `OSC_CYCLE` into `Osc::process()` in `osc.h` (mkII uses **float** mono out, stereo `in`).
3. Map `OSC_PARAM` cases to `setParameter()` (0–100 v1 → use `param_10bit_to_f32` for 0–1023).
4. Map `OSC_NOTEON` / `OSC_NOTEOFF` to `noteOn` / `noteOff` overrides if needed.
5. Pitch: use `w0_` from `setPitch()` instead of `osc_w0(params->pitch)`.
6. Build: `../../tools/build-mkii.sh {slug}`
7. Load `*.nts1mkiiunit` on NTS-1 mkII (Kontrol Editor / loguecli).

See [docs/nts1-mkii-porting.md](../../../docs/nts1-mkii-porting.md).
"""


def scaffold_unit(v1_rel: str, force: bool, skip_wasm: bool, logue_sdk: Path | None) -> Path:
    unit_dir = REPO_ROOT / "src" / v1_rel
    if not unit_dir.is_dir():
        raise SystemExit(f"v1 unit not found: {unit_dir}")

    manifest = load_manifest(unit_dir)
    header = manifest["header"]
    agent = manifest.get("_agent", {})
    slug = agent.get("id") or unit_dir.name.replace("-", "_")
    slug = re.sub(r"[^a-z0-9_]", "_", slug.lower())
    project = re.sub(r"[^a-z0-9_]", "_", slug.lower())[:31]
    out_dir = MKII_OUT / slug
    if out_dir.exists() and not force:
        print(f"skip (exists): {out_dir}", file=sys.stderr)
        return out_dir

    params = header["params"]
    if len(params) > 10:
        raise SystemExit(f"{v1_rel}: mkII allows max 10 params, has {len(params)}")

    presets = agent.get("presets") or []
    default_values = presets[0]["values"] if presets else [int(p[1]) for p in params]

    v1_source = find_v1_source(unit_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / "header.c").write_text(
        render_header_c(header["name"], params, default_values), encoding="utf-8"
    )
    osc_path = out_dir / "osc.h"
    if not osc_h_is_port_complete(osc_path):
        osc_path.write_text(
            render_osc_h(project, params, v1_rel, v1_source, default_values),
            encoding="utf-8",
        )
    else:
        print(f"preserve osc.h (PORT_COMPLETE): {osc_path}", file=sys.stderr)
    (out_dir / "config.mk").write_text(render_config_mk(project, []), encoding="utf-8")
    (out_dir / "Makefile").write_text(render_makefile(), encoding="utf-8")
    (out_dir / "unit.cc").write_text(render_unit_cc(logue_sdk), encoding="utf-8")
    (out_dir / "PORTING.md").write_text(
        render_porting_readme(slug, v1_rel, v1_source), encoding="utf-8"
    )

    meta = {
        "v1_path": v1_rel,
        "v1_source": v1_source,
        "mkii_slug": slug,
        "project": project,
    }
    (out_dir / "mkii.meta.json").write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")

    if not skip_wasm and logue_sdk:
        wasm_src = logue_sdk / "platform" / "nts-1_mkii" / "dummy-osc" / "wasm.cc"
        if wasm_src.is_file():
            shutil.copy2(wasm_src, out_dir / "wasm.cc")

    print(f"scaffolded: {out_dir}")
    return out_dir


def main() -> None:
    ap = argparse.ArgumentParser(description="Scaffold NTS-1 mkII oscillator from v1 unit")
    ap.add_argument("unit", nargs="?", help="v1 path relative to src/, e.g. oscillators/tr808-kick")
    ap.add_argument("--all-bass", action="store_true", help="Scaffold all units from build-all-bass.sh list")
    ap.add_argument("--force", action="store_true", help="Overwrite existing mkII folder")
    ap.add_argument("--skip-wasm", action="store_true")
    ap.add_argument("--logue-sdk", type=Path, default=None)
    args = ap.parse_args()

    logue_sdk = args.logue_sdk
    if logue_sdk is None:
        import os

        env = os.environ.get("LOGUE_SDK")
        if env:
            logue_sdk = Path(env)

    bass_units = [
        "oscillators/tr808-kick",
        "oscillators/west-coast-moog",
        "oscillators/juno-rnb",
        "oscillators/dilla-bass",
        "oscillators/sub-phatty",
        "oscillators/prophet-funk",
        "oscillators/dx7-lately",
        "oscillators/sh101-babyface",
        "oscillators/moog-voyager-se",
        "oscillators/cardo-gfunk",
        "oscillators/larry-june",
        "oscillators/khalifa-haze",
        "oscillators/memphis-juicy",
        "oscillators/ensoniq-eps1",
        "oscillators/template",
        "oscillators/wavetable",
    ]

    if args.all_bass:
        for u in bass_units:
            scaffold_unit(u, args.force, args.skip_wasm, logue_sdk)
        return

    if not args.unit:
        ap.error("provide unit path or --all-bass")

    scaffold_unit(args.unit, args.force, args.skip_wasm, logue_sdk)


if __name__ == "__main__":
    main()
