##############################################################################
# Configuration for Makefile — generated by scaffold-mkii.py
#

PROJECT := khalifa_haze_stoner_bass
PROJECT_TYPE := osc

UCSRC = header.c
UCXXSRC = unit.cc

UINCDIR =
ULIBDIR =
ULIBS = -lm
UDEFS =
