/* Auto-generated by tools/mkii/scaffold-mkii.py — edit dev_id/unit_id before release. */
#include "unit_osc.h"

const __unit_header unit_header_t unit_header = {
    .header_size = sizeof(unit_header_t),
    .target = UNIT_TARGET_PLATFORM | k_unit_module_osc,
    .api = UNIT_API_VERSION,
    .dev_id = 0x0U,
    .unit_id = 0x0U,
    .version = 0x00010000U,
    .name = "Khalifa Haze",
    .num_params = 9,
    .params = {
        {0, 1023, 0, 50, k_unit_param_type_none, 0, 0, 0, {"VIBE"}},
        {0, 1023, 0, 72, k_unit_param_type_none, 0, 0, 0, {"P01X"}},
        {0, 1023, 0, 55, k_unit_param_type_none, 0, 0, 0, {"HAZE"}},
        {0, 1023, 0, 58, k_unit_param_type_none, 0, 0, 0, {"FLOA"}},
        {0, 1023, 0, 48, k_unit_param_type_none, 0, 0, 0, {"WARM"}},
        {0, 1023, 0, 55, k_unit_param_type_none, 0, 0, 0, {"GLID"}},
        {0, 1023, 0, 32, k_unit_param_type_none, 0, 0, 0, {"ATTA"}},
        {0, 1023, 0, 52, k_unit_param_type_none, 0, 0, 0, {"DECA"}},
        {0, 1023, 0, 62, k_unit_param_type_none, 0, 0, 0, {"RELE"}},
        {0, 0, 0, 0, k_unit_param_type_none, 0, 0, 0, {""}},
    },
};
