##############################################################################
# Configuration for Makefile — generated by scaffold_mkii.py
#

PROJECT := ensoniq_eps1_memphis_bass
PROJECT_TYPE := osc

UCSRC = header.c
UCXXSRC = unit.cc

UINCDIR =
ULIBDIR =
ULIBS = _lm
UDEFS =
