/* Auto-generated by tools/mkii/scaffold-mkii.py — edit dev_id/unit_id before release. */
#include "unit_osc.h"

const __unit_header unit_header_t unit_header = {
    .header_size = sizeof(unit_header_t),
    .target = UNIT_TARGET_PLATFORM | k_unit_module_osc,
    .api = UNIT_API_VERSION,
    .dev_id = 0x0U,
    .unit_id = 0x0U,
    .version = 0x00010000U,
    .name = "EPS-1 MEM",
    .num_params = 9,
    .params = {
        {0, 1023, 0, 58, k_unit_param_type_none, 0, 0, 0, {"VIBE"}},
        {0, 1023, 0, 40, k_unit_param_type_none, 0, 0, 0, {"WAVE"}},
        {0, 1023, 0, 52, k_unit_param_type_none, 0, 0, 0, {"DRIF"}},
        {0, 1023, 0, 68, k_unit_param_type_none, 0, 0, 0, {"DARK"}},
        {0, 1023, 0, 45, k_unit_param_type_none, 0, 0, 0, {"RESO"}},
        {0, 1023, 0, 42, k_unit_param_type_none, 0, 0, 0, {"GRIT"}},
        {0, 1023, 0, 25, k_unit_param_type_none, 0, 0, 0, {"GLID"}},
        {0, 1023, 0, 8, k_unit_param_type_none, 0, 0, 0, {"ATTA"}},
        {0, 1023, 0, 55, k_unit_param_type_none, 0, 0, 0, {"TAIL"}},
        {0, 0, 0, 0, k_unit_param_type_none, 0, 0, 0, {""}},
    },
};
