#!/usr/bin/env python3
"""Emit SFZ from InstrumentMapSpec JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def emit_sfz(map_data: dict, out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    instrument_id = map_data["instrumentId"]
    sfz_path = out_dir / f"{instrument_id}.sfz"
    lines: list[str] = [
        "// Generated by disklordz sound-factory emit_sfz.py",
        f"// {map_data.get('name', instrument_id)}",
        "",
    ]
    for i, zone in enumerate(map_data["zones"]):
        rel = zone["samplePath"].replace("\\", "/")
        vol_db = zone.get("volumeDb", 0.0)
        tune = zone.get("tuneCents", 0.0)
        lines.extend(
            [
                f"<group>",
                f"key={zone['rootKey']}",
                f"lokey={zone['loKey']}",
                f"hikey={zone['hiKey']}",
                f"lovel={zone['loVel']}",
                f"hivel={zone['hiVel']}",
                f"pitch_keycenter={zone['rootKey']}",
                f"volume={vol_db:.2f}",
                f"tune={tune:.1f}",
                f"sample={rel}",
                "",
            ]
        )
    sfz_path.write_text("\n".join(lines), encoding="utf-8")
    return sfz_path


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--map", type=Path, required=True, help="instrument-map.json")
    p.add_argument("--out", type=Path, required=True, help="output directory for .sfz")
    args = p.parse_args()
    data = json.loads(args.map.read_text(encoding="utf-8"))
    if data.get("format") != "DISKLORDZ_INSTRUMENT_MAP":
        raise SystemExit("invalid instrument map format")
    path = emit_sfz(data, args.out)
    print(json.dumps({"sfz": str(path)}, indent=2))


if __name__ == "__main__":
    main()
