##############################################################################
# Configuration for Makefile — generated by scaffold-mkii.py
#

PROJECT := west_coast_moog_funk
PROJECT_TYPE := osc

UCSRC = header.c
UCXXSRC = unit.cc

UINCDIR =
ULIBDIR =
ULIBS = -lm
UDEFS =
