##############################################################################
# Configuration for Makefile — generated by scaffold_mkii.py
#

PROJECT := tr808_kick_phonk
PROJECT_TYPE := osc

UCSRC = header.c
UCXXSRC = unit.cc

UINCDIR =
ULIBDIR =
ULIBS = _lm
UDEFS =
