##############################################################################
# Configuration for Makefile — generated by scaffold-mkii.py
#

PROJECT := tr808_kick_phonk
PROJECT_TYPE := osc

UCSRC = header.c
UCXXSRC = unit.cc

UINCDIR =
ULIBDIR =
ULIBS = -lm
UDEFS =
