#!/usr/bin/env python3
"""Verify manifest wiring paths; optionally promote partial → integrated."""

from __future__ import annotations

import argparse
import json
import py_compile
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
MANIFEST = REPO / "disklordz/integrations/manifest.json"
REPORT = REPO / "disklordz/integrations/WIRING_REPORT.md"


def wiring_exists(wiring: str) -> tuple[bool, str]:
    path_part = wiring.split("#")[0].strip()
    p = REPO / path_part
    if "*" in path_part:
        hits = list(REPO.glob(path_part))
        return (len(hits) > 0, f"{len(hits)} match(es)")
    if p.is_file():
        if p.suffix == ".py":
            try:
                py_compile.compile(str(p), doraise=True)
            except py_compile.PyCompileError as e:
                return False, f"syntax error: {e}"
        return True, "file"
    if p.is_dir():
        children = list(p.iterdir())
        return (len(children) > 0, f"dir ({len(children)} entries)")
    return False, "missing"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--write",
        action="store_true",
        help="Promote partial repos to integrated when wiring verifies",
    )
    args = parser.parse_args()

    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    repos = data["repos"]
    lines = [
        "# Integration wiring report",
        "",
        "Generated by `promote-integrations.py`. Re-run after adding stubs.",
        "",
        "| id | repo | status | wiring OK | note |",
        "|----|------|--------|-----------|------|",
    ]
    promoted = 0
    for r in repos:
        if r["status"] == "external":
            lines.append(f"| {r['id']} | {r['repo']} | external | — | operator setup |")
            continue
        ok, note = wiring_exists(r["wiring"])
        mark = "yes" if ok else "**no**"
        lines.append(f"| {r['id']} | {r['repo']} | {r['status']} | {mark} | {note} |")
        if args.write and r["status"] == "partial" and ok:
            r["status"] = "integrated"
            promoted += 1

    if args.write and promoted:
        MANIFEST.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
        print(f"Promoted {promoted} repos to integrated")

    counts = {}
    for r in repos:
        counts[r["status"]] = counts.get(r["status"], 0) + 1
    lines.extend(
        [
            "",
            f"**Totals:** {counts}",
            "",
            "Promote: `python3 disklordz/integrations/scripts/promote-integrations.py --write`",
            "",
        ]
    )
    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {REPORT.relative_to(REPO)}")
    print(counts)
    missing = [r for r in repos if r["status"] == "partial" and not wiring_exists(r["wiring"])[0]]
    if missing:
        print(f"Still partial (missing wiring): {len(missing)}", file=sys.stderr)
        for r in missing:
            print(f"  - {r['id']} {r['repo']}: {r['wiring']}", file=sys.stderr)
        return 1 if not args.write else 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
