##############################################################################
# Configuration for Makefile — generated by scaffold-mkii.py
#

PROJECT := moog_voyager_se1_squelch
PROJECT_TYPE := osc

UCSRC = header.c
UCXXSRC = unit.cc

UINCDIR =
ULIBDIR =
ULIBS = -lm
UDEFS =
