##############################################################################
# Configuration for Makefile — generated by scaffold_mkii.py
#

PROJECT := dilla_type_bass
PROJECT_TYPE := osc

UCSRC = header.c
UCXXSRC = unit.cc

UINCDIR =
ULIBDIR =
ULIBS = _lm
UDEFS =
