##############################################################################
# Configuration for Makefile — generated by scaffold-mkii.py
#

PROJECT := larry_june_bay_cruise_bass
PROJECT_TYPE := osc

UCSRC = header.c
UCXXSRC = unit.cc

UINCDIR =
ULIBDIR =
ULIBS = -lm
UDEFS =
