##############################################################################
# Configuration for Makefile — generated by scaffold-mkii.py
#

PROJECT := cardo_got_wings_gfunk
PROJECT_TYPE := osc

UCSRC = header.c
UCXXSRC = unit.cc

UINCDIR =
ULIBDIR =
ULIBS = -lm
UDEFS =
