##############################################################################
# Configuration for Makefile — generated by scaffold-mkii.py
#

PROJECT := drill_slide_808_tail
PROJECT_TYPE := osc

UCSRC = header.c
UCXXSRC = unit.cc

UINCDIR =
ULIBDIR =
ULIBS = -lm
UDEFS =
