##############################################################################
# Configuration for Makefile — generated by scaffold-mkii.py
#

PROJECT := juno_106_rnb_bass
PROJECT_TYPE := osc

UCSRC = header.c
UCXXSRC = unit.cc

UINCDIR =
ULIBDIR =
ULIBS = -lm
UDEFS =
