/* Auto-generated by tools/mkii/scaffold-mkii.py — edit dev_id/unit_id before release. */
#include "unit_osc.h"

const __unit_header unit_header_t unit_header = {
    .header_size = sizeof(unit_header_t),
    .target = UNIT_TARGET_PLATFORM | k_unit_module_osc,
    .api = UNIT_API_VERSION,
    .dev_id = 0x0U,
    .unit_id = 0x0U,
    .version = 0x00010000U,
    .name = "Juno R&B",
    .num_params = 9,
    .params = {
        {0, 1023, 0, 34, k_unit_param_type_none, 0, 0, 0, {"VIBE"}},
        {0, 1023, 0, 72, k_unit_param_type_none, 0, 0, 0, {"P01X"}},
        {0, 1023, 0, 26, k_unit_param_type_none, 0, 0, 0, {"P02X"}},
        {0, 1023, 0, 44, k_unit_param_type_none, 0, 0, 0, {"CHOR"}},
        {0, 1023, 0, 30, k_unit_param_type_none, 0, 0, 0, {"GLID"}},
        {0, 1023, 0, 10, k_unit_param_type_none, 0, 0, 0, {"ATTA"}},
        {0, 1023, 0, 38, k_unit_param_type_none, 0, 0, 0, {"DECA"}},
        {0, 1023, 0, 36, k_unit_param_type_none, 0, 0, 0, {"RELE"}},
        {0, 1023, 0, 14, k_unit_param_type_none, 0, 0, 0, {"P08X"}},
        {0, 0, 0, 0, k_unit_param_type_none, 0, 0, 0, {""}},
    },
};
